name: main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run Maven verify phase
      continue-on-error: true
      run: mvn --batch-mode --update-snapshots verify
      
    - name: Set output
      id: vars
      run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

    - name: Check output
      run: echo ${{ steps.vars.outputs.short_ref }}

    - name: Update status
      uses: appleboy/telegram-action@master
      with:
        format: html
        disable_web_page_preview: true
        disable_notification: true
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          🛠 [<a href='https://github.com/${{ github.repository }}'>${{ github.repository }}</a> on branch <i>${{ steps.vars.outputs.short_ref }}</i>]
          
          ${{ github.event.commits[0].message }} by "${{ github.actor }}" - <a href='https://github.com/${{ github.repository }}/commit/${{github.sha}}'><b>View Changes</b></a>
